import hou

for mantra in hou.selectedNodes():
	extraImagePlanes = mantra.parm("vm_numaux")
	extraImagePlanes.set("6")
	motionVectors = mantra.parm("vm_variable_plane1")
	motionVectors.set("motion_vector")
	vexType1 = mantra.parm("vm_vextype_plane1")
	vexType1.set("vector")
	channelName1 = mantra.parm("vm_channel_plane1")
	channelName1.set("_motion_vector")
	quantize1 = mantra.parm("vm_quantize_plane1")
	quantize1.set("float")
	sfilter1 = mantra.parm("vm_sfilter_plane1")
	sfilter1.set("alpha")
	pfilter1 = mantra.parm("vm_pfilter_plane1")
	pfilter1.set("minmax_omin")
	pWorld = mantra.parm("vm_variable_plane2")
	pWorld.set("P_world")
	vexType2 = mantra.parm("vm_vextype_plane2")
	vexType2.set("vector")
	channelName2 = mantra.parm("vm_channel_plane2")
	channelName2.set("_Pworld")
	quantize2 = mantra.parm("vm_quantize_plane2")
	quantize2.set("float")
	sfilter2 = mantra.parm("vm_sfilter_plane2")
	sfilter2.set("alpha")
	pfilter2 = mantra.parm("vm_pfilter_plane2")
	pfilter2.set("minmax omedian")
	pObject = mantra.parm("vm_variable_plane3")
	pObject.set("P_object")
	vexType3 = mantra.parm("vm_vextype_plane3")
	vexType3.set("vector")
	channelName3 = mantra.parm("vm_channel_plane3")
	channelName3.set("_Pobject")
	quantize3 = mantra.parm("vm_quantize_plane3")
	quantize3.set("half")
	sfilter3 = mantra.parm("vm_sfilter_plane3")
	sfilter3.set("alpha")
	# pfilter3 = mantra.parm("vm_pfilter_plane3")
	# pfilter3.set("")
	pRef = mantra.parm("vm_variable_plane4")
	pRef.set("P_ref")
	vexType4 = mantra.parm("vm_vextype_plane4")
	vexType4.set("vector")
	channelName4 = mantra.parm("vm_channel_plane4")
	channelName4.set("_Pref")
	quantize4 = mantra.parm("vm_quantize_plane4")
	quantize4.set("float")
	sfilter4 = mantra.parm("vm_sfilter_plane4")
	sfilter4.set("alpha")
	pfilter4 = mantra.parm("vm_pfilter_plane4")
	pfilter4.set("minmax omedian")
	pZ = mantra.parm("vm_variable_plane5")
	pZ.set("Pz")
	vexType5 = mantra.parm("vm_vextype_plane5")
	vexType5.set("float")
	channelName5 = mantra.parm("vm_channel_plane5")
	channelName5.set("_depth")
	quantize5 = mantra.parm("vm_quantize_plane5")
	quantize5.set("float")
	sfilter5 = mantra.parm("vm_sfilter_plane5")
	sfilter5.set("alpha")
	pfilter5 = mantra.parm("vm_pfilter_plane5")
	pfilter5.set("minmax omedian")
	normal = mantra.parm("vm_variable_plane6")
	normal.set("N")
	vexType6 = mantra.parm("vm_vextype_plane6")
	vexType6.set("vector")
	channelName6 = mantra.parm("vm_channel_plane6")
	channelName6.set("_normal")
	quantize6 = mantra.parm("vm_quantize_plane6")
	quantize6.set("float")
	sfilter6 = mantra.parm("vm_sfilter_plane6")
	sfilter6.set("alpha")
	pfilter6 = mantra.parm("vm_pfilter_plane6")
	pfilter6.set("minmax omedian")